image: codesimple/elm

before_script:
  - npm install
  - elm package install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm run build
  artifacts:
    paths:
      - build
  only:
    - master
