image: node

before_script:
  - npm install create-elm-app
  - npx create-elm-app package install
  - npx create-elm-app install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npx create-elm-app build
  artifacts:
    paths:
      - build
  only:
    - master
