image: node

before_script:
  - npm install -g create-elm-app
  - elm-app package install

cache:
  paths:
    - node_modules/

pages:
  script:
    - elm-app build
  artifacts:
    paths:
      - build
  only:
    - master
